#!/bin/bash

set -ex

# ensure we are inside toplevel dir
if ! [ -e requirements.txt ]; then
	echo missing requirements.txt: $PWD
	exit 1
fi

if [ ! -d .env ]; then
	virtualenv --python=python2.7 .env
fi

source .env/bin/activate
easy_install -U distribute
pip install -r requirements.txt
pip install gunicorn
#apt-get install -y setproctitle || true
