#!/bin/bash

set -ex

# ensure we are inside toplevel dir
[ -e requirements.txt ] || cd ..

if [ ! -d .env ]; then
	virtualenv --python=python2.7 .env
fi

source .env/bin/activate
easy_install -U distribute
pip install -r requirements.txt
pip install gunicorn
#apt-get install -y setproctitle || true
