#!/bin/bash

set -ex

# ensure we are inside toplevel dir
[ -e requirements.txt ] || cd ..

if [ ! -d .env ]; then
	virtualenv .env
fi

source .env/bin/activate
pip install -r requirements.txt
pip install gunicorn
apt-get install -y setproctitle || true
